# Generated by Django 5.0.4 on 2024-05-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
